/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.io.IOException;
import java.net.InetSocketAddress;

import com.sun.net.httpserver.*;


import project.handler.roothandler;
import project.handler.sumhandler;

public class App {

    private final String HOSTNAME = "0.0.0.0";
    private final int PORT = 8080;
    private final int BACKLOG = 0;
    private HttpServer server = null;


    // 생성자 생성
    public App() throws IOException{
        createServer(HOSTNAME, PORT);
    }

    public App(int port) throws IOException {
        createServer(HOSTNAME, port);
    }
    public App(String host, int port) throws IOException {
        createServer(host, port);
    }


    //서버 생성
    private void createServer(String host, int port) throws IOException{

        //HTTP SERVER 생성
        this.server = HttpServer.create(new InetSocketAddress(host, port),BACKLOG);
        server.createContext("/", new roothandler());
        server.createContext("/sum", new sumhandler());


    }

    public void start(){
        this.server.setExecutor(null);
        this.server.start();
        System.out.println("Server started on port"+PORT);

    }

    //서버 중지
    public void stop(int delay){
        server.stop(delay);
    }




    public static void main(String[] args) {
        System.out.println("Hello world");
        App app = null;

        try{
            System.out.println("server start... ");
            //서버 생성
            app = new App(5678);
            app.start();

        }catch (Exception e){
            e.printStackTrace();
            throw new RuntimeException(e);

        }



    }
}
